branches:
  only:
    - master
    - '/v[0-9]+(\.[0-9]+)*/'
skip_non_tags: true
clone_depth: 1
environment:
  nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: |
  - yarn global add firebase-tools
  - yarn install --frozen-lockfile --network-timeout=500000
build_script:
  - yarn run lint
  - yarn run build
  # - yarn run test
test: "off"
cache:
  - node_modules -> yarn.lock
  - "%LOCALAPPDATA%\\Yarn"
deploy_script:
  - ps: |
      if ($env:firebase_token)
      {
        iex "firebase deploy --token $env:firebase_token"
      }
